# Auto-generated by compose2nix.

{ lib, ... }:

{
  imports = [ ./compose2nix-common.nix ];

  networking.firewall.allowedTCPPorts = [ 8089 ];
  networking.firewall.allowedUDPPorts = [ 5004 65001 ];

  # Ensure mount directories exist before the container starts
  systemd.tmpfiles.rules = [
    "d /mnt/prodigy/mojo/dvr/channels/config 0755 root root -"
    "d /mnt/prodigy/mojo/dvr/channels/recordings 0755 root root -"
  ];

  # Containers
  virtualisation.oci-containers.containers."channels-dvr" = {
    image = "fancybits/channels-dvr:latest";
    volumes = [
      "/mnt/prodigy/mojo/dvr/channels/config:/channels-dvr:rw"
      "/mnt/prodigy/mojo/dvr/channels/recordings:/shares/DVR:rw"
    ];
    ports = [
      "8089:8089/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri:/dev/dri:rwm"
      "--group-add=303"
      "--group-add=44"
      "--network=host"
    ];
  };
  systemd.services."podman-channels-dvr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "on-failure";
    };
    startLimitBurst = 10;
    unitConfig = {
      StartLimitIntervalSec = lib.mkOverride 90 "infinity";
      RequiresMountsFor = "/mnt/prodigy";
    };
    partOf = [
      "podman-compose-channels-dvr-root.target"
    ];
    wantedBy = [
      "podman-compose-channels-dvr-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-channels-dvr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
