# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."jellyfin" = {
    image = "linuxserver/jellyfin:10.11.6";
    environment = {
      "DOCKER_MODS" = "linuxserver/mods:jellyfin-opencl-intel";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/Chicago";
    };
    volumes = [
      "/DATA/AppData/jellyfin/config:/config:rw"
      "/DATA/Media:/Media:rw"
      "/opt/vc/lib:/opt/vc/lib:rw"
      "/mnt/prodigy:/prodigy:rw"
    ];
    ports = [
      "8097:8096/tcp"
      "8921:8920/tcp"
      "7359:7359/tcp"
      "1901:1900/tcp"
    ];
    cmd = [  ];
    labels = {
      "icon" = "https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Jellyfin/icon.png";
      "stack-back.volumes" = "true";
      "stack-back.volumes.include" = "config";
      "stack-back.volumes.stop-during-backup" = "true";
    };
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri/:/dev/dri/:rwm"
      "--dns=1.1.1.1"
      "--group-add=109"
      "--memory-reservation=268435456b"
      "--memory=8132755456b"
      "--network-alias=jellyfin"
      "--network=bridge"
    ];
  };
  systemd.services."podman-jellyfin" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-jellyfin-root.target"
    ];
    wantedBy = [
      "podman-compose-jellyfin-root.target"
    ];
  };
  virtualisation.oci-containers.containers."jellyfin-backups" = {
    image = "ghcr.io/lawndoc/stack-back:v1.4.2";
    environment = {
      "AWS_ACCESS_KEY_ID" = "REDACTED";
      "AWS_SECRET_ACCESS_KEY" = "REDACTED";
      "CRON_SCHEDULE" = "\"0 5 * * *\"";
      "RESTIC_KEEP_DAILY" = "7";
      "RESTIC_KEEP_MONTHLY" = "12";
      "RESTIC_KEEP_WEEKLY" = "4";
      "RESTIC_KEEP_YEARLY" = "2";
      "RESTIC_PASSWORD" = "REDACTED";
      "RESTIC_REPOSITORY" = "s3:s3.us-west-004.backblazeb2.com/restic-menagerie/jellyfin";
      "TZ" = "America/Chicago";
    };
    volumes = [
      "/var/run/docker.sock:/tmp/docker.sock:ro"
      "jellyfin_cache:/cache:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=backups"
      "--network=jellyfin_default"
    ];
  };
  systemd.services."podman-jellyfin-backups" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-jellyfin_default.service"
      "podman-volume-jellyfin_cache.service"
    ];
    requires = [
      "podman-network-jellyfin_default.service"
      "podman-volume-jellyfin_cache.service"
    ];
    partOf = [
      "podman-compose-jellyfin-root.target"
    ];
    wantedBy = [
      "podman-compose-jellyfin-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-jellyfin_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f jellyfin_default";
    };
    script = ''
      podman network inspect jellyfin_default || podman network create jellyfin_default
    '';
    partOf = [ "podman-compose-jellyfin-root.target" ];
    wantedBy = [ "podman-compose-jellyfin-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-jellyfin_cache" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect jellyfin_cache || podman volume create jellyfin_cache
    '';
    partOf = [ "podman-compose-jellyfin-root.target" ];
    wantedBy = [ "podman-compose-jellyfin-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-jellyfin-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
