# Auto-generated by compose2nix.

{ lib, inputs, ... }:

{
  imports = [ ./compose2nix-common.nix ];

  networking.firewall.allowedTCPPorts = [ 5274 ];

  # Containers
  virtualisation.oci-containers.containers."octo-fiesta" = {
    image = "ghcr.io/v1ck3s/octo-fiesta";
    environment = {
      "ASPNETCORE_ENVIRONMENT" = "Production";
      "ASPNETCORE_URLS" = "http://+:5274";
      "Library__DownloadPath" = "/app/downloads";
      "Qobuz__Quality" = "";
      "Qobuz__UserAuthToken" = "";
      "Qobuz__UserId" = "";
      "SquidWTF__InstanceTimeoutSeconds" = "5";
      # https://github.com/V1ck3s/octo-fiesta/wiki/Configuration#squidwtf-quality-options
      "SquidWTF__Quality" = "7";
      "SquidWTF__Source" = "Qobuz";
      "Subsonic__AutoUpgradeQuality" = "false";
      "Subsonic__CacheDurationHours" = "1";
      "Subsonic__DownloadMode" = "Track";
      "Subsonic__EnableExternalPlaylists" = "true";
      "Subsonic__ExplicitFilter" = "All";
      "Subsonic__FolderTemplate" = "";
      "Subsonic__MusicService" = "SquidWTF";
      "Subsonic__PlaylistsDirectory" = "playlists";
      "Subsonic__StorageMode" = "Permanent";
      "Subsonic__Url" = "http://localhost:4533";
      "Yandex__IncludeUnavailable" = "false";
      "Yandex__Language" = "";
      "Yandex__OAuthToken" = "";
      "Yandex__Quality" = "";
    };
    volumes = [
      "${inputs.constants.musicDir}:/app/downloads:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-octo-fiesta" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-octo-fiesta-root.target"
    ];
    wantedBy = [
      "podman-compose-octo-fiesta-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-octo-fiesta-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
