# https://taskfile.dev

version: '3'


tasks:
  batgirl-deploy:
    dir: ./config
    cmds:
      # bootstrap: - sudo nix --extra-experimental-features nix-command --extra-experimental-features flakes run nix-darwin/nix-darwin-25.05#darwin-rebuild -- switch --flake .
      - sudo darwin-rebuild switch --flake .
