# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  batgirl-deploy:
    dir: ./hosts/batgirl
    cmds:
      - sudo nix run nix-darwin/nix-darwin-25.05#darwin-rebuild -- switch --flake .
